python main.py ../refactor_code_base/src/resource/database/acs-aem-commons.db
python main.py ../refactor_code_base/src/resource/database/acs-packaging.db
python main.py ../refactor_code_base/src/resource/database/activiti.db
python main.py ../refactor_code_base/src/resource/database/aem-core-wcm-components.db
python main.py ../refactor_code_base/src/resource/database/airbyte-platform.db
python main.py ../refactor_code_base/src/resource/database/alluxio.db
python main.py ../refactor_code_base/src/resource/database/ambari.db
python main.py ../refactor_code_base/src/resource/database/antlr4.db
python main.py ../refactor_code_base/src/resource/database/a_refactoring-toy-example.db
python main.py ../refactor_code_base/src/resource/database/automq.db
python main.py ../refactor_code_base/src/resource/database/avro.db
python main.py ../refactor_code_base/src/resource/database/azure-sdk-for-java.db
python main.py ../refactor_code_base/src/resource/database/beam.db
python main.py ../refactor_code_base/src/resource/database/buck.db
python main.py ../refactor_code_base/src/resource/database/camel.db
python main.py ../refactor_code_base/src/resource/database/camel-spring-boot.db
python main.py ../refactor_code_base/src/resource/database/cas.db
python main.py ../refactor_code_base/src/resource/database/checkstyle.db
python main.py ../refactor_code_base/src/resource/database/commons-lang.db
python main.py ../refactor_code_base/src/resource/database/cxf.db
python main.py ../refactor_code_base/src/resource/database/intellij-community.db